use_directory_urls: false
site_name: Cennznet-js
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
  - yaml
  - rust
nav:
- Api Promise:
  - 'Home': 'api/README.md'
- Wallet:
  - 'Home': 'wallet/README.md'
