version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.tmp/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn test --coverage
      - store_test_results:
          path: coverage
      - setup_remote_docker
      - run:
          name: Run integration tests
          command: |
            docker run -d -p 0.0.0.0:9944:9944 cennznet/cennznet:rc1 --dev --ws-external
            # start-up delay
            sleep 10
            yarn test:e2e

